[general]
import = ["colors.toml"]

[env]
TERM = "screen-256color"

[window]
startup_mode = "Fullscreen"
# blur = true
# opacity = 0.5

[font]
size = 13
normal      = { family = "Google Sans Code", style = "ExtraBold" }
bold        = { family = "Google Sans Code", style = "Bold" }
italic      = { family = "Google Sans Code", style = "Italic" }
bold_italic = { family = "Google Sans Code", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen"},]
